import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext();

export const languages = {
  ckb: { label: 'کوردی', dir: 'rtl', flag: '🇹🇯' },
  en: { label: 'English', dir: 'ltr', flag: '🇬🇧' },
  ar: { label: 'العربية', dir: 'rtl', flag: '🇮🇶' },
};

const translations = {
  ckb: {
    // Nav
    nav_home: 'سەرەکی',
    nav_scan: 'پشکنین',
    nav_trending: 'زیادبوونی مەترسی',
    nav_community: 'کۆمەڵگە',
    nav_learn: 'فێربوون',
    nav_dashboard: 'داشبۆرد',
    nav_login: 'چوونەژوورەوە',
    nav_profile: 'پرۆفایل',
    nav_logout: 'دەرچوون',
    nav_admin: 'بەڕێوەبردن',
    // Brand
    brand_name: 'FakeCheck Kurdistan',
    tagline: 'پێش کلیککردن پشکنە',
    // Hero
    hero_title: 'FakeCheck Kurdistan',
    hero_subtitle: 'پێش کلیککردن پشکنە',
    hero_desc: 'خۆت بپارێزە لە لینکی گومانلێکراو، نامەی فێڵکاری، هەوڵی فیشینگ، ناوەڕۆکی ساختە و فێڵی ئۆنلاین.',
    hero_cta: 'ئێستا پشکنە',
    // Tools
    tools_title: 'ئامرازەکانی پشکنین',
    tool_link: 'پشکنەری لینک',
    tool_link_desc: 'لینکی گومانلێکراو بپشکنە بۆ نیشانەکانی فیشینگ و فێڵ.',
    tool_screenshot: 'پشکنەری وێنەی شاشەت',
    tool_screenshot_desc: 'وێنەی شاشەت باربکە بۆ دۆزینەوەی ناوەڕۆکی فێڵکار.',
    tool_message: 'پشکنەری نامە',
    tool_message_desc: 'نامەی SMS، WhatsApp، Telegram و ئیمەیڵ بپشکنە.',
    tool_news: 'پشکنەری هەواڵ',
    tool_news_desc: 'هەواڵ و ناوەڕۆکی هەواڵ بپشکنە بۆ زانیاری هەڵە.',
    open_scanner: 'کردنەوەی پشکنەر',
    // Stats
    stats_total_scans: 'کۆی پشکنینەکان',
    stats_dangerous: 'ناوەڕۆکی مەترسیدار',
    stats_suspicious: 'ناوەڕۆکی گومانلێکراو',
    stats_reports: 'ڕاپۆرتی کۆمەڵگە',
    // Scam alerts
    latest_alerts: 'دوایین ئاگادارکردنەوەکانی فێڵ',
    view_all: 'هەمووی ببینە',
    // Scanner
    paste_url: 'لینک دابنێ',
    paste_message: 'نامە دابنێ',
    analyze_link: 'شیکارکردنی لینک',
    analyze_message: 'شیکارکردنی نامە',
    analyze_screenshot: 'شیکارکردنی وێنە',
    analyze_news: 'شیکارکردنی هەواڵ',
    analyzing: 'شیکارکردن...',
    upload_image: 'وێنە بارت بکە',
    upload_hint: 'PNG, JPG, JPEG, WEBP - تا ٥MB',
    article_url: 'لینکی هەواڵ',
    news_headline: 'سەردێڕی هەواڵ',
    article_text: 'دەقی هەواڵ',
    // Result
    risk_score: 'نمرەی مەترسی',
    risk_level_low: 'مەترسی کەم',
    risk_level_suspicious: 'گومانلێکراو',
    risk_level_high: 'مەترسی بەرز',
    risk_summary: 'پوختەی مەترسی',
    detected_warnings: 'نیشانە ئاگادارکردنەوەکانی دۆزراوە',
    recommended_action: 'کرداری پێشنیارکراو',
    share_result: 'هاوبەشکردنی ئەنجام',
    save_scan: 'پاشەکەوتکردنی پشکنین',
    report_scam: 'ڕاپۆرتی فێڵ',
    scan_another: 'پشکنینی دیکە',
    warning_signs: 'نیشانە ئاگادارکردنەوەکان',
    disclaimer: 'ئەمە هەڵسەنگاندنی مەترسی خۆکارە. تکایە زانیاری گرنگ بە شێوەی سەربەخۆ پشتڕاست بکەرەوە.',
    external_unavailable: 'پشتڕاستکردنەوەی دەرەکی بەردەست نییە.',
    // Progress
    progress_uploading: 'بارکردن',
    progress_reading: 'خوێندنەوەی ناوەڕۆک',
    progress_analyzing: 'شیکارکردنی نیشانەکانی پاراستن',
    progress_calculating: 'حیسابکردنی مەترسی',
    progress_preparing: 'ئامادەکردنی ئەنجام',
    // Community
    community_title: 'ڕاپۆرتەکانی کۆمەڵگە',
    community_desc: 'فێڵ و ناوەڕۆکی گومانلێکراو ڕاپۆرت بکە بۆ یارمەتیدانی کۆمەڵگە.',
    report_scam_title: 'ڕاپۆرتی فێڵ بدە',
    field_title: 'ناونیشان',
    field_scam_type: 'جۆری فێڵ',
    field_description: 'وەسف',
    field_url: 'لینکی گومانلێکراو',
    field_phone: 'ژمارەی تەلەفۆن',
    field_screenshot: 'وێنەی شاشەت',
    field_region: 'وڵات / ناوچە',
    field_platform: 'پلاتفۆرم',
    submit_report: 'ناردنی ڕاپۆرت',
    status_pending: 'چاوەڕێ',
    status_approved: 'پەسەندکراو',
    status_rejected: 'ڕەتکراو',
    // Trending
    trending_title: 'فێڵە زیادبووەکان',
    trending_desc: 'نوێترین فێڵەکان لە کۆمەڵگەدا.',
    status_verified: 'فێڵی پشتڕاستکراو',
    status_suspicious_t: 'گومانلێکراو',
    status_investigating: 'لەژێر لێکۆڵینەوە',
    trending_badge: 'زیادبوو',
    report_count: 'ژمارەی ڕاپۆرت',
    first_reported: 'یەکەم ڕاپۆرت',
    latest_report: 'دوایین ڕاپۆرت',
    // Learn
    learn_title: 'فێربوون',
    learn_desc: 'فێربە چۆن خۆت بپارێزیت لە فێڵ و هێلە ئۆنلاینەکان.',
    // Dashboard
    dashboard_title: 'داشبۆرد',
    recent_scans: 'پشکنینە دوایینەکان',
    saved_results: 'ئەنجامە پاشەکەوتکراوەکان',
    submitted_reports: 'ڕاپۆرتە نێردراوەکان',
    security_tips: 'ئامۆژگاری پاراستن',
    // Auth
    login: 'چوونەژوورەوە',
    register: 'خۆتۆمارکردن',
    // Footer
    footer_tagline: 'پێش کلیککردن پشکنە',
    privacy_policy: 'سیاسەتی تایبەتمەندی',
    terms: 'مەرجەکان',
    contact: 'پەیوەندی',
    footer_tips: 'ئامۆژگاری پاراستن',
    // Common
    loading: 'بارکردن...',
    no_data: 'هیچ داتایەک نییە',
    back_home: 'گەڕانەوە بۆ سەرەکی',
    search: 'گەڕان',
    cancel: 'هەڵوەشاندنەوە',
    save: 'پاشەکەوت',
    delete: 'سڕینەوە',
    approve: 'پەسەندکردن',
    reject: 'ڕەتکردنەوە',
    view: 'بینین',
  },
  en: {
    nav_home: 'Home',
    nav_scan: 'Scan',
    nav_trending: 'Trending Scams',
    nav_community: 'Community',
    nav_learn: 'Learn',
    nav_dashboard: 'Dashboard',
    nav_login: 'Login',
    nav_profile: 'Profile',
    nav_logout: 'Logout',
    nav_admin: 'Admin',
    brand_name: 'FakeCheck Kurdistan',
    tagline: 'Check Before You Click',
    hero_title: 'FakeCheck Kurdistan',
    hero_subtitle: 'Check Before You Click',
    hero_desc: 'Protect yourself from suspicious links, scam messages, phishing attempts, fake content, and online fraud.',
    hero_cta: 'Scan Now',
    tools_title: 'Scanning Tools',
    tool_link: 'Link Scanner',
    tool_link_desc: 'Analyze suspicious URLs for phishing and scam indicators.',
    tool_screenshot: 'Screenshot Scanner',
    tool_screenshot_desc: 'Upload a screenshot to detect scam content.',
    tool_message: 'Message Scanner',
    tool_message_desc: 'Scan SMS, WhatsApp, Telegram, and email messages.',
    tool_news: 'News Checker',
    tool_news_desc: 'Check news and articles for misinformation signals.',
    open_scanner: 'Open Scanner',
    stats_total_scans: 'Total Scans',
    stats_dangerous: 'Dangerous Content',
    stats_suspicious: 'Suspicious Content',
    stats_reports: 'Community Reports',
    latest_alerts: 'Latest Scam Alerts',
    view_all: 'View All',
    paste_url: 'Paste URL',
    paste_message: 'Paste message',
    analyze_link: 'Analyze Link',
    analyze_message: 'Analyze Message',
    analyze_screenshot: 'Analyze Screenshot',
    analyze_news: 'Analyze News',
    analyzing: 'Analyzing...',
    upload_image: 'Upload Image',
    upload_hint: 'PNG, JPG, JPEG, WEBP - up to 5MB',
    article_url: 'Article URL',
    news_headline: 'News Headline',
    article_text: 'Article Text',
    risk_score: 'Risk Score',
    risk_level_low: 'Low Risk',
    risk_level_suspicious: 'Suspicious',
    risk_level_high: 'High Risk',
    risk_summary: 'Risk Summary',
    detected_warnings: 'Detected Warning Signs',
    recommended_action: 'Recommended Action',
    share_result: 'Share Result',
    save_scan: 'Save Scan',
    report_scam: 'Report Scam',
    scan_another: 'Scan Another',
    warning_signs: 'Warning Signs',
    disclaimer: 'This is an automated risk assessment. Please verify important information independently.',
    external_unavailable: 'External verification unavailable.',
    progress_uploading: 'Uploading',
    progress_reading: 'Reading Content',
    progress_analyzing: 'Analyzing Security Signals',
    progress_calculating: 'Calculating Risk',
    progress_preparing: 'Preparing Result',
    community_title: 'Community Reports',
    community_desc: 'Report scams and suspicious content to help the community.',
    report_scam_title: 'Report a Scam',
    field_title: 'Title',
    field_scam_type: 'Scam Type',
    field_description: 'Description',
    field_url: 'Suspicious URL',
    field_phone: 'Phone Number',
    field_screenshot: 'Screenshot',
    field_region: 'Country / Region',
    field_platform: 'Platform',
    submit_report: 'Submit Report',
    status_pending: 'Pending',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    trending_title: 'Trending Scams',
    trending_desc: 'The latest scams spreading in the community.',
    status_verified: 'Verified Scam',
    status_suspicious_t: 'Suspicious',
    status_investigating: 'Under Investigation',
    trending_badge: 'Trending',
    report_count: 'Reports',
    first_reported: 'First Reported',
    latest_report: 'Latest Report',
    learn_title: 'Learn',
    learn_desc: 'Learn how to protect yourself from online scams and threats.',
    dashboard_title: 'Dashboard',
    recent_scans: 'Recent Scans',
    saved_results: 'Saved Results',
    submitted_reports: 'Submitted Reports',
    security_tips: 'Security Tips',
    login: 'Login',
    register: 'Register',
    footer_tagline: 'Check Before You Click',
    privacy_policy: 'Privacy Policy',
    terms: 'Terms',
    contact: 'Contact',
    footer_tips: 'Security Tips',
    loading: 'Loading...',
    no_data: 'No data available',
    back_home: 'Back to Home',
    search: 'Search',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    approve: 'Approve',
    reject: 'Reject',
    view: 'View',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_scan: 'فحص',
    nav_trending: 'الاحتيال الرائج',
    nav_community: 'المجتمع',
    nav_learn: 'تعلم',
    nav_dashboard: 'لوحة التحكم',
    nav_login: 'تسجيل الدخول',
    nav_profile: 'الملف الشخصي',
    nav_logout: 'تسجيل الخروج',
    nav_admin: 'الإدارة',
    brand_name: 'FakeCheck Kurdistan',
    tagline: 'تحقق قبل النقر',
    hero_title: 'FakeCheck Kurdistan',
    hero_subtitle: 'تحقق قبل النقر',
    hero_desc: 'احمِ نفسك من الروابط المشبوهة ورسائل الاحتيال ومحاولات التصيد والمحتوى المزيف والاحتيال عبر الإنترنت.',
    hero_cta: 'افحص الآن',
    tools_title: 'أدوات الفحص',
    tool_link: 'فاحص الروابط',
    tool_link_desc: 'حلل الروابط المشبوهة للكشف عن علامات التصيد والاحتيال.',
    tool_screenshot: 'فاحص لقطة الشاشة',
    tool_screenshot_desc: 'ارفع لقطة شاشة للكشف عن المحتوى الاحتيالي.',
    tool_message: 'فاحص الرسائل',
    tool_message_desc: 'فحص رسائل SMS و WhatsApp و Telegram والبريد الإلكتروني.',
    tool_news: 'فاحص الأخبار',
    tool_news_desc: 'فحص الأخبار والمقالات للكشف عن معلومات مضللة.',
    open_scanner: 'فتح الفاحص',
    stats_total_scans: 'إجمالي الفحوصات',
    stats_dangerous: 'محتوى خطير',
    stats_suspicious: 'محتوى مشبوه',
    stats_reports: 'تقارير المجتمع',
    latest_alerts: 'أحدث تنبيهات الاحتيال',
    view_all: 'عرض الكل',
    paste_url: 'الصق الرابط',
    paste_message: 'الصق الرسالة',
    analyze_link: 'تحليل الرابط',
    analyze_message: 'تحليل الرسالة',
    analyze_screenshot: 'تحليل لقطة الشاشة',
    analyze_news: 'تحليل الأخبار',
    analyzing: 'جاري التحليل...',
    upload_image: 'رفع صورة',
    upload_hint: 'PNG, JPG, JPEG, WEBP - حتى 5 ميجابايت',
    article_url: 'رابط المقال',
    news_headline: 'عنوان الخبر',
    article_text: 'نص المقال',
    risk_score: 'درجة المخاطر',
    risk_level_low: 'مخاطر منخفضة',
    risk_level_suspicious: 'مشبوه',
    risk_level_high: 'مخاطر عالية',
    risk_summary: 'ملخص المخاطر',
    detected_warnings: 'علامات التحذير المكتشفة',
    recommended_action: 'الإجراء الموصى به',
    share_result: 'مشاركة النتيجة',
    save_scan: 'حفظ الفحص',
    report_scam: 'الإبلاغ عن احتيال',
    scan_another: 'فحص آخر',
    warning_signs: 'علامات التحذير',
    disclaimer: 'هذا تقييم مخاطر آلي. يرجى التحقق من المعلومات المهمة بشكل مستقل.',
    external_unavailable: 'التحقق الخارجي غير متوفر.',
    progress_uploading: 'رفع',
    progress_reading: 'قراءة المحتوى',
    progress_analyzing: 'تحليل إشارات الأمان',
    progress_calculating: 'حساب المخاطر',
    progress_preparing: 'تحضير النتيجة',
    community_title: 'تقارير المجتمع',
    community_desc: 'أبلغ عن الاحتيال والمحتوى المشبوه لمساعدة المجتمع.',
    report_scam_title: 'الإبلاغ عن احتيال',
    field_title: 'العنوان',
    field_scam_type: 'نوع الاحتيال',
    field_description: 'الوصف',
    field_url: 'رابط مشبوه',
    field_phone: 'رقم الهاتف',
    field_screenshot: 'لقطة شاشة',
    field_region: 'البلد / المنطقة',
    field_platform: 'المنصة',
    submit_report: 'إرسال التقرير',
    status_pending: 'قيد الانتظار',
    status_approved: 'معتمد',
    status_rejected: 'مرفوض',
    trending_title: 'الاحتيال الرائج',
    trending_desc: 'أحدث عمليات الاحتيال المنتشرة في المجتمع.',
    status_verified: 'احتيال موثق',
    status_suspicious_t: 'مشبوه',
    status_investigating: 'قيد التحقيق',
    trending_badge: 'رائج',
    report_count: 'التقارير',
    first_reported: 'أول بلاغ',
    latest_report: 'آخر بلاغ',
    learn_title: 'تعلم',
    learn_desc: 'تعلم كيف تحمي نفسك من الاحتيال والتهديدات عبر الإنترنت.',
    dashboard_title: 'لوحة التحكم',
    recent_scans: 'أحدث الفحوصات',
    saved_results: 'النتائج المحفوظة',
    submitted_reports: 'التقارير المرسلة',
    security_tips: 'نصائح الأمان',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    footer_tagline: 'تحقق قبل النقر',
    privacy_policy: 'سياسة الخصوصية',
    terms: 'الشروط',
    contact: 'اتصل بنا',
    footer_tips: 'نصائح الأمان',
    loading: 'جاري التحميل...',
    no_data: 'لا توجد بيانات',
    back_home: 'العودة للرئيسية',
    search: 'بحث',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    approve: 'اعتماد',
    reject: 'رفض',
    view: 'عرض',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('fck_lang') || 'ckb');

  useEffect(() => {
    const config = languages[lang];
    document.documentElement.lang = lang;
    document.documentElement.dir = config.dir;
    localStorage.setItem('fck_lang', lang);
  }, [lang]);

  const t = useCallback((key) => {
    return (translations[lang] && translations[lang][key]) || translations.en[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir: languages[lang].dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}